site_name: Tá Na Mesa
site_description: Repositório da documentação da aplicação Tá Na Mesa desenvolvido na disciplina de Desenho e Arquitetura de Software
copyright: Copyright &copy; 2021, <a href="https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs" target="_blank">Tá Na Mesa</a>
repo_url: https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs
site_dir: site
theme:
  name: "material"
  logo: assets/img/logo-dagua.png
  favicon: assets/img/logo-dagua.png
  lang:
    - pt
  palette:
    primary: red
  features:
    - navigation.tabs

nav:
  - Base:
    - Projeto Não Orientado a Abordagens Específicas:
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Design-Sprint.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Rich-Picture.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Mapa-Mental.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Ishikawa.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Lexicos.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/5W2H.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Plano-Riscos.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/TAP.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Prototipo-Baixa-Fidelidade.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Priorizacao-MOSCOW.md
      
    - Processos / Metodologias / Abordagens:
      - 1-Base/Processos-Metodologias-Abordagens/Metodologia.md
      - 1-Base/Processos-Metodologias-Abordagens/Modelagem-BPMN.md
    
    - Extras:
      - 1-Base/extras/Identidade-Visual.md
      - 1-Base/extras/Politica-Contribuicao.md
      - 1-Base/extras/Personas.md
      - Técnicas de Elicitação:
        - 1-Base/extras/Tecnicas-Elicitacao/Brainstorming.md
        - 1-Base/extras/Tecnicas-Elicitacao/Benchmarking.md
        - 1-Base/extras/Tecnicas-Elicitacao/Introspeccao.md
        - 1-Base/extras/Tecnicas-Elicitacao/Storytelling.md
        - 1-Base/extras/Tecnicas-Elicitacao/Questionario.md
        - 1-Base/extras/Tecnicas-Elicitacao/NFR-Framework.md
        - Entrevistas:
          - 1-Base/extras/Tecnicas-Elicitacao/Entrevistas/Roteiro-Entrevista.md
          - 1-Base/extras/Tecnicas-Elicitacao/Entrevistas/Entrevista-1.md
          - 1-Base/extras/Tecnicas-Elicitacao/Entrevistas/Entrevista-2.md
          - 1-Base/extras/Tecnicas-Elicitacao/Entrevistas/Entrevista-3.md
          - 1-Base/extras/Tecnicas-Elicitacao/Entrevistas/Entrevista-4.md
          - 1-Base/extras/Tecnicas-Elicitacao/Entrevistas/Entrevista-5.md

  - Modelagem:
    - Modelagem Ágil:
      - 2-Modelagem/Modelagem Ágil/Backlog.md
    - Notação UML - Diagramas Dinâmicos:
      - 2-Modelagem/Diagramas-Dinamicos/Diagrama-de-atividade.md
      - 2-Modelagem/Diagramas-Dinamicos/diagrama-estado.md
    - Notação UML - Diagramas Estáticos:
      - teste //Depois apaga quando tiver um documento, pq sem ele não deixa criar pasta
    - Extras:
      - 2-Modelagem/extras/Casos-de-Uso.md
      - 2-Modelagem/extras/Modelo-Dados.md
      - 2-Modelagem/extras/arquitetura.md

  - Iniciativas Extras:
      - Documentação das Sprints:
          - Sprint 01:
              - 5-Extra/Sprints/Sprint-01/Planning-01.md
              - 5-Extra/Sprints/Sprint-01/Review-01.md
          - Sprint 02:
              - 5-Extra/Sprints/Sprint-02/Planning-02.md

  - Apresentações:
      - Apresentacoes/entrega-1.md

plugins:
  - search

extra_css:
  - assets/css/extra.css
  - assets/css/landing-page.css

extra_javascript:
  - assets/js/jquery.min.js
  - assets/js/jquery.zoom.min.js
  - assets/js/extra.js

dev_addr: '0.0.0.0:8000'
