site_name: Tá Na Mesa
site_description: Repositório da documentação da aplicação Tá Na Mesa desenvolvido na disciplina de Desenho e Arquitetura de Software
copyright: Copyright &copy; 2021, <a href="https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs" target="_blank">Tá Na Mesa</a>
repo_url: https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs
site_dir: site
theme:
  name: "material"
  logo: assets/img/logo-dagua.png
  favicon: assets/img/logo-dagua.png
  lang:
    - pt
  palette:
    primary: red
  features:
    - navigation.tabs

plugins:
  - search

extra_css:
  - assets/css/extra.css
  - assets/css/landing-page.css

extra_javascript:
  - assets/js/jquery.min.js
  - assets/js/jquery.zoom.min.js
  - assets/js/extra.js


dev_addr: '0.0.0.0:8000'
