site_name: Tá Na Mesa
site_description: Repositório da documentação da aplicação Tá Na Mesa desenvolvido na disciplina de Desenho e Arquitetura de Software
copyright: Copyright &copy; 2021, <a href="https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs" target="_blank">Tá Na Mesa</a>
repo_url: https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs
site_dir: site
theme:
  name: "material"
  logo: assets/img/logo-dagua.png
  favicon: assets/img/logo-dagua.png
  lang:
    - pt
  palette:
    primary: red
  features:
    - navigation.tabs

nav:
  - Base:
    - Projeto Não Orientado a Abordagens Específicas:
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Design-Sprint.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Rich-Picture.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Mapa-Mental.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Ishikawa.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Lexicos.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/5W2H.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Plano-Riscos.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Prototipo-Baixa-Fidelidade.md
      - Técnicas de Elicitação:
        - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Brainstorming.md
        - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Benchmarking.md
        - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Introspeccao.md
        - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Storytelling.md
        - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Questionario.md
        - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/NFR-Framework.md
        - Entrevistas:
          - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Entrevistas/Roteiro-Entrevista.md
          - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Entrevistas/Entrevista-1.md
          - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Entrevistas/Entrevista-2.md
          - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Entrevistas/Entrevista-3.md
          - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Entrevistas/Entrevista-4.md
          - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Tecnicas-Elicitacao/Entrevistas/Entrevista-5.md
      - 1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Priorizacao-MOSCOW.md
      
    - Processos / Metodologias / Abordagens:
      - 1-Base/Processos-Metodologias-Abordagens/Metodologia.md
      - 1-Base/Processos-Metodologias-Abordagens/Modelagem-BPMN.md
    
    - Extras:
      - 1-Base/extras/TAP.md
      - 1-Base/extras/Identidade-Visual.md
      - 1-Base/extras/Politica-Contribuicao.md
      - 1-Base/extras/Personas.md

  - Modelagem:
    - Notação UML - Diagramas Estáticos:
      - 2-Modelagem/Diagramas-Estaticos/diagrama-de-classes.md
      - 2-Modelagem/Diagramas-Estaticos/Diagrama-de-Pacotes.md
      - 2-Modelagem/Diagramas-Estaticos/Diagrama-de-componentes.md

    - Notação UML - Diagramas Dinâmicos:
      - 2-Modelagem/Diagramas-Dinamicos/Diagrama-Sequencia.md
      - 2-Modelagem/Diagramas-Dinamicos/Diagrama-de-atividade.md
      - 2-Modelagem/Diagramas-Dinamicos/Diagrama-estado.md
      - 2-Modelagem/Diagramas-Dinamicos/Diagrama-comunicacao.md

    - Modelagem Ágil:
      - 2-Modelagem/Modelagem Ágil/Backlog.md
    
    - Extras:
      - 2-Modelagem/extras/Casos-de-Uso.md
      - 2-Modelagem/extras/Modelo-Dados.md
      - 2-Modelagem/extras/arquitetura.md
      - 2-Modelagem/extras/Prototipo-Alta-Fidelidade.md

  - Padrões de Projeto:
    - GRASP(s):
      - 3-Padroes-de-Projeto/GRASPs/Padroes-Adotados-no-Projeto.md
      - 3-Padroes-de-Projeto/GRASPs/Padroes-Nao-Adotados-no-Projeto.md
    - GoF(s):
      - Criacionais:
        - 3-Padroes-de-Projeto/GoFs/Criacionais/Padroes-Adotados-no-Projeto.md
        - 3-Padroes-de-Projeto/GoFs/Criacionais/Padroes-Nao-Adotados-no-Projeto.md
      - Estruturais:
        - 3-Padroes-de-Projeto/GoFs/Estruturais/Padroes-Adotados-no-Projeto.md
        - 3-Padroes-de-Projeto/GoFs/Estruturais/Padroes-Nao-Adotados-no-Projeto.md
      - Comportamentais:
        - 3-Padroes-de-Projeto/GoFs/Comportamentais/Padroes-Adotados-no-Projeto.md
        - 3-Padroes-de-Projeto/GoFs/Comportamentais/Padroes-Nao-Adotados-no-Projeto.md
    - Extras(Emergentes):
      - 3-Padroes-de-Projeto/Emergentes/Padroes-Adotados-no-Projeto.md

    - Extras:
      - ''

  - Sprints:
    - Sprint 01:
      - Sprints/Sprint-01/Planning-01.md
      - Sprints/Sprint-01/Review-01.md
    - Sprint 02:
      - Sprints/Sprint-02/Planning-02.md
      - Sprints/Sprint-02/Review-02.md
    - Sprint 03:
      - Sprints/Sprint-03/Planning-03.md
      - Sprints/Sprint-03/Review-03.md
    - Sprint 04:
      - Sprints/Sprint-04/Planning-04.md
      - Sprints/Sprint-04/Review-04.md
    - Sprint 05:
      - Sprints/Sprint-05/Planning-05.md
      - Sprints/Sprint-05/Review-05.md

  - Apresentações:
      - Apresentacoes/entrega-1.md
      - Apresentacoes/entrega-2.md

plugins:
  - search

extra_css:
  - assets/css/extra.css
  - assets/css/landing-page.css

extra_javascript:
  - assets/js/jquery.min.js
  - assets/js/jquery.zoom.min.js
  - assets/js/extra.js

dev_addr: '0.0.0.0:8000'
